### ISSUE TITLE
Justify doesn't work on Firefox

### ISSUE THREAD

**Issue by scileo** [JohnMcLear/ep_align#10]
Hello,
First I want to thank you because you do a good job. Your plugin works very well on my etherpad server. There is just a little issue. When I create a paragraph and define it's formatting to "justify", it works on Chromium, Vivaldi, Chrome (to my mind, every blink-based browser), but on firefox, it doesn't work.
I hope you will correct it soon, this plugin is just awesome !
This is the "correct" result which can be seen on Vivaldi : 
![vivaldi](https://cloud.githubusercontent.com/assets/25402018/22396549/91b43df2-e55c-11e6-8857-43c0a19f7fcb.png)
This is the "uncorrect", which is displayed on firefox :
![firefox](https://cloud.githubusercontent.com/assets/25402018/22396548/9067359e-e55c-11e6-87c3-d5fd59c73278.png)

Have a nice day, please forgive my english.

**Comment by poVoq** [comment]
Same here. In addition it seems to break .pdf export.

**Comment by JohnMcLear** [comment]
Not gonna be looking into this any time soon I'm afraid so if someone else can look at it that would be useful

**Comment by JohnMcLear** [comment]
Fixed.
