### ISSUE TITLE
Settings file needs to be modified

### ISSUE THREAD

**Issue by jjellinek** [JohnMcLear/ep_align#13]
Maybe this is obvious, but took me a little while to figure out. Perhaps the readme could be updated to explain that the etherpad-lite settings file needs the toolbar section uncommented and the following added to it:-

      ["alignLeft", "alignCenter", "alignJustify", "alignRight"],

(It did for me anyway)

**Comment by JohnMcLear** [comment]
It shouldn't.  Someone broke something in Etherpad, will fix..  :|

**Comment by JohnMcLear** [comment]
Fixed, ish, I had to manually squish the buttons into the UI.  Note they don't look great on older versions of etherpad any more.  Something RE adding buttons was broken upstream and also I discovered a huge bug if you follow your suggestion then remove the plugin!
