### ISSUE TITLE
Caret automatically moves to left

### ISSUE THREAD

**Issue by deepsaggas** [JohnMcLear/ep_align#7]
Steps to Reproduce:
1) Clone etherpad-lite
2) Install ep_align plugin
3) open a new pad with default text
4) click such that your caret is at the starting of first line just before "welcome".
5) click on center align button, text gets center aligned.
6) now click anywhere on the same line "Welcome to Etherpad!". You will notice that caret automatically moves to the left till it reaches the starting position.

**Comment by JohnMcLear** [comment]
What browser/os / version of Etherpad?

**Comment by deepsaggas** [comment]
Browser: Google Chrome: Version 40.0.2214.111 (64-bit) / Firefox 35.0.1
OS: Ubuntu
Etherpad: "1.5.2" (checked in package.json)

**Comment by JohnMcLear** [comment]
Confirmed.

**Comment by JohnMcLear** [comment]
Used bisect, caused by 789ab6f492863211166b4feb51f0cb95284e052a

**Comment by JohnMcLear** [comment]
tnx for reporting.  Easy fix.

**Comment by deepsaggas** [comment]
Thanks for making so many wonderful plugins :+1:
